import React, { useEffect, useState } from 'react';
import { Shield, CheckCircle, AlertTriangle, Flag, TrendingUp, Droplets, Brain, Printer, X } from 'lucide-react';
import { Chart as ChartJS, LineElement, PointElement, LinearScale, CategoryScale, Tooltip, Legend, Filler } from 'chart.js';
import { Line } from 'react-chartjs-2';
import { useWaterRisk } from '../hooks/useWaterRisk.js';

ChartJS.register(LineElement, PointElement, LinearScale, CategoryScale, Tooltip, Legend, Filler);

const DAYS = ['Apr 19', 'Apr 20', 'Apr 21', 'Apr 22', 'Apr 23', 'Apr 24', 'Apr 25'];

function GaugeBar({ value, max = 100, color }) {
  const [width, setWidth] = useState(0);
  useEffect(() => { const t = setTimeout(() => setWidth((value / max) * 100), 80); return () => clearTimeout(t); }, [value, max]);
  return (
    <div style={{ height: 6, background: 'var(--bg-elevated)', borderRadius: 3, overflow: 'hidden', marginTop: 4 }}>
      <div style={{ height: '100%', width: `${width}%`, background: color, borderRadius: 3, transition: 'width 0.8s ease-out' }} />
    </div>
  );
}

// Colour helpers for water risk scores
const scoreColor = (score) => score > 0.55 ? 'var(--red)' : score > 0.3 ? 'var(--amber)' : 'var(--green)';
const riskBg    = (level) => level === 'flood' ? 'var(--blue-light,#EFF6FF)' : level === 'drought' ? 'var(--amber-light)' : level === 'both' ? 'var(--red-light)' : 'var(--green-light)';
const riskBorder= (level) => level === 'flood' ? '#BFDBFE' : level === 'drought' ? 'var(--amber-border)' : level === 'both' ? 'var(--red-border)' : 'var(--green-border)';
const riskLabel = (level) => ({ flood:'Flood risk nearby', drought:'Drought stress nearby', both:'Flood + Drought', ok:'Water stable', unknown:'Checking…' })[level] || 'Checking…';

export default function FieldDetailPanel({ field, onClose, onAction, isMobile = false }) {
  const [displayedText, setDisplayedText] = useState('');
  const [chartMounted, setChartMounted] = useState(false);
  const [flagModal, setFlagModal] = useState(false);
  const [flagNote, setFlagNote] = useState('');
  const [flagged, setFlagged] = useState(false);
  const { waterBodies, riskLevel, insight, insightModel, loading: wrLoading, error: wrError } = useWaterRisk(field?.id);

  const printPDF = () => {
    const printContent = document.getElementById('field-detail-print-area');
    if (!printContent) return;
    const win = window.open('', '_blank', 'width=800,height=900');
    win.document.write(`<!DOCTYPE html><html><head>
      <title>AquaGuard – Field ${field.id} Report</title>
      <style>
        body { font-family: system-ui, sans-serif; padding: 32px; color: #0F1F3D; max-width: 720px; margin: 0 auto; }
        h1 { font-size: 20px; margin-bottom: 4px; } h2 { font-size: 14px; color: #4A6080; margin: 20px 0 8px; border-bottom: 1px solid #E2E8F2; padding-bottom: 4px; }
        table { width: 100%; border-collapse: collapse; font-size: 13px; }
        td, th { padding: 8px 10px; text-align: left; border-bottom: 1px solid #E2E8F2; }
        th { color: #8FA3BF; font-size: 11px; text-transform: uppercase; }
        .badge { display:inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 600; }
        .anomaly { background: #FEE2E2; color: #DC2626; } .warning { background: #FEF3C7; color: #D97706; } .ok { background: #DCFCE7; color: #16A34A; }
        .insight { background: #F0FDFA; border-left: 3px solid #0098A6; padding: 12px; border-radius: 4px; font-size: 13px; line-height: 1.6; margin-top: 8px; }
        .footer { margin-top: 40px; font-size: 11px; color: #8FA3BF; border-top: 1px solid #E2E8F2; padding-top: 12px; }
      </style></head><body>
      ${printContent.innerHTML}
      <div class="footer">Generated by AquaGuard · ${new Date().toLocaleString('hu-HU')} · Pest County Water Authority</div>
      </body></html>`);
    win.document.close();
    win.focus();
    setTimeout(() => { win.print(); win.close(); }, 500);
  };

  const confirmFlag = () => {
    onAction('flag', field);
    setFlagged(true);
    setFlagModal(false);
    setFlagNote('');
  };

  useEffect(() => {
    if (!field) return;
    setDisplayedText('');
    let i = 0;
    const text = field.systemVerdict;
    const timer = setInterval(() => {
      i++;
      setDisplayedText(text.slice(0, i));
      if (i >= text.length) clearInterval(timer);
    }, 28);
    return () => clearInterval(timer);
  }, [field?.id]);

  useEffect(() => {
    const t = setTimeout(() => setChartMounted(true), 120);
    return () => clearTimeout(t);
  }, [field?.id]);

  if (!field) return null;

  const waste = field.actualUse - field.cwr;

  const chartData = {
    labels: DAYS,
    datasets: [
      {
        label: 'Actual use (L)',
        data: field.history,
        borderColor: '#DC2626',
        backgroundColor: 'rgba(220,38,38,0.06)',
        borderWidth: 2,
        pointRadius: 3,
        fill: true,
        tension: 0.4,
      },
      {
        label: 'CWR Estimate (L)',
        data: field.cwrHistory,
        borderColor: '#16A34A',
        borderWidth: 2,
        borderDash: [5, 4],
        pointRadius: 2,
        fill: false,
        tension: 0.4,
      },
    ],
  };

  const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    animation: { duration: 700 },
    plugins: {
      legend: { labels: { color: '#4A6080', font: { family: 'DM Mono', size: 10 }, boxWidth: 18 } },
      tooltip: {
        backgroundColor: '#fff',
        borderColor: '#E2E8F2',
        borderWidth: 1,
        titleColor: '#0F1F3D',
        bodyColor: '#4A6080',
        padding: 10,
        callbacks: { label: ctx => ` ${ctx.dataset.label}: ${ctx.parsed.y.toLocaleString()} L` },
      },
    },
    scales: {
      x: { ticks: { color: '#8FA3BF', font: { size: 10, family: 'DM Mono' } }, grid: { color: '#E2E8F2' } },
      y: { ticks: { color: '#8FA3BF', font: { size: 10, family: 'DM Mono' } }, grid: { color: '#E2E8F2' } },
    },
  };

  const statusCls = field.status === 'anomaly' ? 'pill-anomaly' : field.status === 'warning' ? 'pill-warning' : 'pill-ok';

  return (
    <>
    <div style={{
      position: 'fixed',
      top: 52,
      right: 0,
      bottom: isMobile ? 56 : 0,
      left: isMobile ? 0 : 'auto',
      width: isMobile ? '100%' : 390,
      background: 'var(--bg-surface)',
      borderLeft: isMobile ? 'none' : '1px solid var(--border)',
      boxShadow: isMobile ? 'none' : '-4px 0 20px rgba(0,0,0,0.08)',
      display: 'flex', flexDirection: 'column',
      zIndex: 800,
      animation: 'slideInRight 0.25s ease-out',
      overflowY: 'auto',
    }}>
      {/* Header */}
      <div style={{ padding: '14px 18px', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }}>
          <button
            onClick={onClose}
            style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 5, fontSize: 13, fontFamily: 'var(--font-ui)' }}
          >
            ← Map
          </button>
          <div style={{ display: 'flex', gap: 8 }}>
            <button
              className="btn-outline"
              onClick={printPDF}
              style={{ width: 'auto', padding: '5px 11px', fontSize: 12 }}
            >Export PDF</button>
            <button
              className="btn-outline"
              style={{ width: 'auto', padding: '5px 11px', fontSize: 12, color: flagged ? 'var(--green)' : 'var(--amber)', borderColor: flagged ? 'var(--green-border)' : '#FDE68A' }}
              onClick={() => flagged ? null : setFlagModal(true)}
            >
              <Flag size={11} /> {flagged ? 'Flagged ✓' : 'Flag'}
            </button>
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}>
          <h2 style={{ fontFamily: 'var(--font-mono)', fontSize: 16, color: 'var(--text-primary)', fontWeight: 600 }}>
            Field {field.id}
          </h2>
          <span className={`pill ${statusCls}`}>
            {field.status === 'anomaly' ? 'Anomaly' : field.status === 'warning' ? 'Warning' : 'Efficient'} · +{field.wastePercent}% over CWR
          </span>
        </div>
        <div style={{ fontSize: 12, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
          {field.owner} · {field.crop} · {field.district} · {field.area} ha
        </div>
        <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>
          Last updated: 25 Apr, 08:14
        </div>
      </div>

      {/* 7-day chart */}
      <div style={{ padding: '14px 18px', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
        <div style={{ fontSize: 10, fontFamily: 'var(--font-mono)', color: 'var(--text-muted)', letterSpacing: '0.08em', marginBottom: 8 }}>
          7-DAY CONSUMPTION vs CWR · L/day
        </div>
        <div style={{ height: 130 }}>
          {chartMounted && <Line data={chartData} options={chartOptions} />}
        </div>
      </div>

      {/* 4 metric cards */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, padding: '14px 18px', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
        {[
          { label: 'Actual use today',  value: `${field.actualUse.toLocaleString()} L`, color: 'var(--red)' },
          { label: 'Satellite CWR',     value: `${field.cwr.toLocaleString()} L`,       color: 'var(--green)' },
          { label: 'Waste delta',        value: `+${waste.toLocaleString()} L`,           color: 'var(--red)', sub: `+${field.wastePercent}%` },
          { label: 'Days flagged',       value: `${field.daysAnomaly} days`,              color: field.daysAnomaly > 0 ? 'var(--red)' : 'var(--green)' },
        ].map(({ label, value, color, sub }) => (
          <div key={label} style={{ background: 'var(--bg-elevated)', borderRadius: 7, padding: '10px 12px', border: '1px solid var(--border)' }}>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>{label}</div>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: 16, color, fontWeight: 500 }}>{value}</div>
            {sub && <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>{sub}</div>}
          </div>
        ))}
      </div>

      {/* Satellite gauges */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, padding: '14px 18px', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
        <div style={{ background: 'var(--teal-light)', border: '1px solid rgba(0,152,166,0.2)', borderRadius: 7, padding: '10px 12px' }}>
          <div style={{ fontSize: 10, fontFamily: 'var(--font-mono)', color: 'var(--teal)', letterSpacing: '0.06em', marginBottom: 4 }}>SENTINEL-2 NDVI</div>
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: 20, color: 'var(--teal)', fontWeight: 600 }}>{field.ndvi}</div>
          <GaugeBar value={field.ndvi * 100} color="var(--teal)" />
          <div style={{ fontSize: 10, color: 'var(--text-muted)', marginTop: 4 }}>Vegetation index · Apr 25</div>
        </div>
        <div style={{
          background: field.soilMoisture === 'Saturated' ? 'var(--red-light)' : field.soilMoisture === 'High' ? 'var(--amber-light)' : 'var(--green-light)',
          border: `1px solid ${field.soilMoisture === 'Saturated' ? 'var(--red-border)' : field.soilMoisture === 'High' ? 'var(--amber-border)' : 'var(--green-border)'}`,
          borderRadius: 7, padding: '10px 12px',
        }}>
          <div style={{ fontSize: 10, fontFamily: 'var(--font-mono)', color: 'var(--text-muted)', letterSpacing: '0.06em', marginBottom: 4 }}>SENTINEL-1 SOIL</div>
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: 14, fontWeight: 600,
            color: field.soilMoisture === 'Saturated' ? 'var(--red)' : field.soilMoisture === 'High' ? 'var(--amber)' : 'var(--green)',
          }}>{field.soilMoisture.toUpperCase()}</div>
          <GaugeBar
            value={field.soilMoisture === 'Saturated' ? 100 : field.soilMoisture === 'High' ? 78 : field.soilMoisture === 'Normal' ? 50 : 25}
            color={field.soilMoisture === 'Saturated' ? 'var(--red)' : field.soilMoisture === 'High' ? 'var(--amber)' : 'var(--green)'}
          />
          <div style={{ fontSize: 10, color: 'var(--text-muted)', marginTop: 4 }}>SAR backscatter · Apr 25</div>
        </div>
      </div>

      {/* Galileo OSNMA */}
      <div style={{ padding: '14px 18px', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
        <div style={{
          background: 'var(--teal-light)',
          border: '1px solid rgba(0,152,166,0.25)',
          borderLeft: '3px solid var(--teal)',
          borderRadius: 7, padding: '10px 12px',
          display: 'flex', gap: 10,
        }}>
          <Shield size={16} style={{ color: 'var(--teal)', flexShrink: 0, marginTop: 1 }} />
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 3 }}>
              <CheckCircle size={11} style={{ color: 'var(--teal)' }} />
              <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--teal)', fontWeight: 600 }}>
                🔐 METER VERIFIED · GALILEO OSNMA
              </span>
            </div>
            <div style={{ fontSize: 12, color: 'var(--text-secondary)' }}>
              GPS matches registered location · Last signed: {field.galileoTimestamp}
            </div>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-muted)', marginTop: 3 }}>
              SIG: {field.galileoHash}
            </div>
          </div>
        </div>
      </div>

      {/* ── Water Risk KNN card ── */}
      <div style={{ padding: '14px 18px', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 10 }}>
          <Droplets size={13} style={{ color: 'var(--teal)' }} />
          <span style={{ fontSize: 10, fontFamily: 'var(--font-mono)', color: 'var(--text-muted)', letterSpacing: '0.08em' }}>NEAREST WATER BODIES · KNN k=3</span>
        </div>

        {wrLoading && !waterBodies && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {[1,2,3].map(i => <div key={i} className="skeleton" style={{ height: 36, borderRadius: 6 }} />)}
          </div>
        )}

        {wrError && !waterBodies && (
          <div style={{ fontSize: 12, color: 'var(--text-muted)', fontStyle: 'italic' }}>Backend offline — water risk unavailable</div>
        )}

        {waterBodies && (
          <>
            <div style={{
              display: 'inline-flex', alignItems: 'center', gap: 6,
              background: riskBg(riskLevel), border: `1px solid ${riskBorder(riskLevel)}`,
              borderRadius: 20, padding: '4px 10px', marginBottom: 10,
            }}>
              <span style={{ fontSize: 12, fontWeight: 600, color: riskLevel === 'ok' ? 'var(--green)' : riskLevel === 'flood' ? '#1D4ED8' : 'var(--amber)' }}>
                {riskLabel(riskLevel)}
              </span>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {waterBodies.map((wb, i) => (
                <div key={wb.id || i} style={{
                  display: 'grid', gridTemplateColumns: '1fr auto auto',
                  alignItems: 'center', gap: 8,
                  background: 'var(--bg-elevated)', borderRadius: 6, padding: '8px 10px',
                  border: '1px solid var(--border)',
                }}>
                  <div>
                    <div style={{ fontSize: 12, color: 'var(--text-primary)', fontWeight: 500 }}>{wb.name}</div>
                    <div style={{ fontSize: 10, color: 'var(--text-muted)', marginTop: 1 }}>{wb.distance_km} km · {wb.type.replace('_',' ')}</div>
                  </div>
                  <div style={{ textAlign: 'center' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: scoreColor(wb.flood_score), fontWeight: 600 }}>F {wb.flood_score.toFixed(2)}</div>
                    <div style={{ fontSize: 9, color: 'var(--text-muted)' }}>flood</div>
                  </div>
                  <div style={{ textAlign: 'center' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: scoreColor(wb.drought_score), fontWeight: 600 }}>D {wb.drought_score.toFixed(2)}</div>
                    <div style={{ fontSize: 9, color: 'var(--text-muted)' }}>drought</div>
                  </div>
                </div>
              ))}
            </div>
          </>
        )}
      </div>

      {/* ── AI Insight card ── */}
      <div style={{ padding: '14px 18px', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 10 }}>
          <Brain size={13} style={{ color: 'var(--teal)' }} />
          <span style={{ fontSize: 10, fontFamily: 'var(--font-mono)', color: 'var(--text-muted)', letterSpacing: '0.08em' }}>AI WATER ADVISOR</span>
          {insightModel && (
            <span style={{ marginLeft: 'auto', fontSize: 9, fontFamily: 'var(--font-mono)', color: 'var(--text-muted)', background: 'var(--bg-elevated)', padding: '2px 6px', borderRadius: 4, border: '1px solid var(--border)' }}>
              {insightModel === 'rule-based-fallback' ? 'rule-based' : 'GPT-4.1'}
            </span>
          )}
        </div>

        {wrLoading && !insight && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            <div className="skeleton" style={{ height: 14, borderRadius: 4, width: '95%' }} />
            <div className="skeleton" style={{ height: 14, borderRadius: 4, width: '80%' }} />
            <div className="skeleton" style={{ height: 14, borderRadius: 4, width: '88%' }} />
          </div>
        )}

        {insight && (
          <div style={{
            background: 'var(--teal-light)', border: '1px solid rgba(0,152,166,0.2)',
            borderLeft: '3px solid var(--teal)',
            borderRadius: 7, padding: '11px 13px',
          }}>
            <p style={{ fontSize: 12, color: 'var(--text-primary)', lineHeight: 1.7, margin: 0 }}>
              {insight}
            </p>
          </div>
        )}

        {!wrLoading && !insight && !wrError && (
          <div style={{ fontSize: 12, color: 'var(--text-muted)', fontStyle: 'italic' }}>Insight not available</div>
        )}
      </div>

      {/* System verdict */}
      <div style={{ padding: '14px 18px', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
        <div style={{ fontSize: 10, fontFamily: 'var(--font-mono)', color: 'var(--text-muted)', letterSpacing: '0.08em', marginBottom: 8 }}>SYSTEM VERDICT</div>
        <div style={{ background: 'var(--bg-elevated)', borderRadius: 7, padding: '12px', minHeight: 70 }}>
          <p style={{ fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--text-primary)', lineHeight: 1.7 }}>
            {displayedText}
            <span style={{ borderRight: '2px solid var(--teal)', marginLeft: 1, animation: 'livePulse 1s step-end infinite' }}>&nbsp;</span>
          </p>
        </div>
      </div>

      {/* Action buttons */}
      <div style={{ padding: '14px 18px', flexShrink: 0 }}>
        <div style={{ fontSize: 10, fontFamily: 'var(--font-mono)', color: 'var(--text-muted)', letterSpacing: '0.08em', marginBottom: 10 }}>
          RECOMMENDED ACTIONS
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {(field.actionUrgency === 'critical' || field.actionUrgency === 'high') ? (
            <button className="btn-danger" onClick={() => onAction('cease', field)}>
              <AlertTriangle size={14} /> Issue Cease Irrigation Order
            </button>
          ) : field.actionUrgency === 'medium' ? (
            <button
              onClick={() => onAction('warn', field)}
              style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, padding: '9px 16px', background: 'var(--amber-light)', color: 'var(--amber)', border: '1px solid var(--amber-border)', borderRadius: 7, fontFamily: 'var(--font-ui)', fontSize: 13, fontWeight: 600, cursor: 'pointer', width: '100%' }}
            >
              <AlertTriangle size={14} /> Send Warning Notice
            </button>
          ) : (
            <button className="btn-outline" onClick={() => onAction('monitor', field)}>
              <TrendingUp size={14} /> Monitor &amp; Flag Next Cycle
            </button>
          )}

          {/* Flag for Inspection — shows modal */}
          {flagged ? (
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '9px 16px', background: 'var(--amber-light)', borderRadius: 7, border: '1px solid var(--amber-border)' }}>
              <Flag size={14} style={{ color: 'var(--amber)' }} />
              <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--amber)' }}>Flagged for inspection ✓</span>
            </div>
          ) : (
            <button className="btn-outline" onClick={() => setFlagModal(true)}>
              <Flag size={14} /> Flag for Inspection
            </button>
          )}

          {/* PDF Export */}
          <button
            onClick={printPDF}
            style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, padding: '9px 16px', background: 'none', border: '1px solid var(--border)', borderRadius: 7, fontFamily: 'var(--font-ui)', fontSize: 13, color: 'var(--text-secondary)', cursor: 'pointer', width: '100%', transition: 'all 0.15s' }}
            onMouseEnter={e => { e.currentTarget.style.borderColor = 'var(--teal)'; e.currentTarget.style.color = 'var(--teal)'; }}
            onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.color = 'var(--text-secondary)'; }}
          >
            <Printer size={14} /> Export PDF Report
          </button>

          <button
            onClick={() => window.open('https://www.ovit.hu/vizgyazdalkodas', '_blank')}
            style={{ background: 'none', border: 'none', color: 'var(--teal)', fontSize: 13, cursor: 'pointer', textAlign: 'left', padding: '4px 0', fontFamily: 'var(--font-ui)' }}
          >
            See inspection workflow ↗
          </button>
        </div>
      </div>
    </div>

    {/* Hidden area used by printPDF — structured for clean print output */}
    <div id="field-detail-print-area" style={{ display: 'none' }}>
      <h1>AquaGuard Field Report — Field {field.id}</h1>
      <p style={{ color: '#4A6080', margin: '4px 0 16px' }}>{field.owner} · {field.crop} · {field.area} ha · Pest County</p>
      <h2>Water Usage</h2>
      <table>
        <tbody>
          <tr><th>Actual Use</th><td>{field.actualUse.toLocaleString()} L/day</td></tr>
          <tr><th>CWR Estimate</th><td>{field.cwr.toLocaleString()} L/day</td></tr>
          <tr><th>Over-extraction</th><td>+{(field.actualUse - field.cwr).toLocaleString()} L (+{field.wastePercent}%)</td></tr>
          <tr><th>Monthly Quota Used</th><td>{field.quotaUsed}%</td></tr>
          <tr><th>Soil Moisture</th><td>{field.soilMoisture}</td></tr>
          <tr><th>Status</th><td><span className={field.status}>{field.status.toUpperCase()}</span></td></tr>
        </tbody>
      </table>
      {insight && (
        <><h2>AI Water Management Insight</h2><div className="insight">{insight}</div></>
      )}
      {waterBodies && waterBodies.length > 0 && (
        <><h2>Nearest Water Bodies (KNN)</h2>
        <table>
          <thead><tr><th>Name</th><th>Distance (km)</th><th>Flood Score</th><th>Drought Score</th></tr></thead>
          <tbody>{waterBodies.map(wb => (
            <tr key={wb.id}><td>{wb.name}</td><td>{wb.distance_km}</td><td>{(wb.flood_score ?? 0).toFixed(3)}</td><td>{(wb.drought_score ?? 0).toFixed(3)}</td></tr>
          ))}</tbody>
        </table></>
      )}
      <h2>System Verdict</h2>
      <p>{field.systemVerdict}</p>
      <h2>Recommended Action</h2>
      <p>{field.recommendedAction}</p>
    </div>

    {/* Flag Confirmation Modal */}
    {flagModal && (
      <div style={{ position: 'fixed', inset: 0, background: 'rgba(15,31,61,0.45)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 2000, animation: 'fadeScaleIn 0.18s ease-out' }}>
        <div className="card" style={{ borderRadius: 12, padding: '28px 28px', maxWidth: 420, width: '90%', boxShadow: '0 16px 48px rgba(0,0,0,0.2)' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <Flag size={16} style={{ color: 'var(--amber)' }} />
              <span style={{ fontSize: 15, fontWeight: 600, color: 'var(--text-primary)' }}>Flag for Inspection</span>
            </div>
            <button onClick={() => setFlagModal(false)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)', padding: 4 }}><X size={16} /></button>
          </div>
          <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6, marginBottom: 14 }}>
            Flag <strong>Field {field.id}</strong> ({field.owner}) for manual on-site inspection. This will be logged in the inspector activity record.
          </p>
          <label style={{ fontSize: 12, color: 'var(--text-secondary)', display: 'block', marginBottom: 6 }}>Inspector notes (optional)</label>
          <textarea
            value={flagNote}
            onChange={e => setFlagNote(e.target.value)}
            placeholder="Reason for flagging, suspected issue, priority level…"
            rows={3}
            style={{ width: '100%', padding: '10px 12px', border: '1px solid var(--border)', borderRadius: 7, fontFamily: 'var(--font-ui)', fontSize: 13, color: 'var(--text-primary)', background: 'var(--bg-elevated)', outline: 'none', resize: 'vertical', boxSizing: 'border-box', marginBottom: 16 }}
            onFocus={e => e.target.style.borderColor = 'var(--teal)'}
            onBlur={e =>  e.target.style.borderColor = 'var(--border)'}
          />
          <div style={{ display: 'flex', gap: 10 }}>
            <button
              onClick={confirmFlag}
              style={{ flex: 1, padding: '10px', background: 'var(--amber)', color: '#fff', border: 'none', borderRadius: 7, fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font-ui)' }}
            >
              🚩 Confirm Flag
            </button>
            <button className="btn-outline" onClick={() => setFlagModal(false)} style={{ flex: 1, padding: '10px' }}>Cancel</button>
          </div>
        </div>
      </div>
    )}
  </>
  );
}
